---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hls-app
spec:
  selector:
    matchLabels:
      app: flask-hls-app
  template:
    metadata:
      labels:
        app: flask-hls-app
    spec:
      containers:
        - name: flask
          image: prabhanjan953/flask-hls-app:1.0.1
          command:
            - sh
            - -c
          args:
            - |
              echo "127.0.0.1 localhost" >> /etc/hosts &&
              apk add socat &&
              socat TCP-LISTEN:6379,fork,reuseaddr TCP:redis:6379 &
          ports:
            - containerPort: 5000
          env:
            - name: NGINX_URL
              value: http://localhost:8081/videos/
            - name: REDIS_HOST
              value: redis;
            - name: VIDEO_SERVER_HOST
              value: 127.0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: flask-hls-app
spec:
  type: NodePort
  selector:
    app: flask-hls-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
