{{- if .Values.flask.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-app
spec:
  template:
    spec:
      containers:
      - name: flask
        image: {{ .Values.flask.image | default "prabhanjan953/flask-hls-app:latest" }}
        command:
        - sh
        - -c
        args:
        - |
          echo "127.0.0.1 localhost" >> /etc/hosts &&
          apk add socat &&
          socat TCP-LISTEN:6379,fork,reuseaddr TCP:{{ .Release.Name }}-redis-service:6379 &
        ports:
        - containerPort: 5000
        env:
        - name: NGINX_URL
          value: {{ .Values.flask.nginxUrl | quote }}
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-service
spec:
  type: {{ .Values.flask.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.flask.service.port | default 5000 }}
      targetPort: {{ .Values.flask.service.targetPort | default 5000 }}
      {{- if eq (.Values.flask.service.type | default "NodePort") "NodePort" }}
      nodePort: {{ .Values.flask.service.nodePort | default 30500 }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-flask-app
{{- end }}