{{- if .Values.nginx.enabled }}
---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nginx-storage
  labels:
    app: {{ .Release.Name }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.nginx.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.nginx.storage.size }}
---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    app: {{ .Release.Name }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  nginx.conf: |
    {{- .Values.nginx.config | nindent 4 }}
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.nginx.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.deployment.image.repository }}:{{ .Values.nginx.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.deployment.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nginx.service.port }}
        volumeMounts:
        - name: video-storage
          mountPath: "/usr/share/nginx/html"
        - name: nginx-config
          mountPath: "/etc/nginx/conf.d/default.conf"
          subPath: nginx.conf
      volumes:
      - name: video-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-nginx-storage
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  labels:
    app: {{ .Release.Name }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-nginx
{{- end }}