{{- if .Values.redis.enabled }}
---
# Redis ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-config
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  redis.conf: |
    appendonly {{ .Values.redis.config.appendonly }}
    save {{ .Values.redis.config.save }}
    maxmemory {{ .Values.redis.config.maxmemory }}
    maxmemory-policy {{ .Values.redis.config.maxmemory_policy }}
---
# Redis Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secrets
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  {{- if .Values.redis.auth.enabled }}
  REDIS_USER: {{ .Values.redis.auth.user | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- end }}
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.redis.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.deployment.image.repository }}:{{ .Values.redis.deployment.image.tag }}"
        ports:
        - containerPort: {{ .Values.redis.service.port }}
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        {{- if .Values.redis.auth.enabled }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-redis-secrets
        {{- end }}
        command: ["redis-server"]
        args: ["/usr/local/etc/redis/redis.conf"]
        resources:
          limits:
            memory: {{ .Values.redis.deployment.resources.limits.memory }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-redis-config
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-service
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-redis
{{- end }}