apiVersion: v1
entries:
  directdeploy:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-09T15:38:08.511161+05:30"
    description: A Helm chart for Kubernetes
    digest: a94e1fcbd21a35d17403ba5b27a8a8c4a6c0b063842cc148ad81de8eb0dab754
    name: directdeploy
    type: application
    urls:
    - directdeploy-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-09T15:38:08.5086873+05:30"
